name: flutter_map_tappable_polyline
description: A flutter_map plugin that adds Polyline class with onTap event
version: 5.0.0
homepage: https://github.com/OwnWeb/flutter_map_tappable_polyline

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map:
    git:
      url: https://github.com/Rado996/flutter_map_my_fork.git
      ref: updatedRelease
  latlong2: ^0.9.0

dev_dependencies:
  pedantic: ^1.11.1
